### ISSUE TITLE
Add warning about 3.x removing the CLI?

### ISSUE THREAD

**Issue by developit** [sindresorhus/pretty-bytes#13]
I cringe when I see these `-cli` repos come trickle into my Github feed, but I understand the logic and can appreciate the need to isolate dependencies.

When this happened with `gzip-size` all my projects broke after updating - and that's fine since it was a major version change - but there was very little in the way of a "hey, you're trying to invoke a non-CLI module now". It might be worth warning people - semver helps and all, but lots of people use hacky stuff like `npm-check-updates -u` without realizing what they are doing.

Even something like retaining a `bin/pretty-bytes` that just prints a removal notice would be nice.

**Comment by sindresorhus** [comment]
This is something I wish npm would solve for everyone by having some kind of built-in changelog support. Though, to be honest, if you bump major without checking for changes you kinda get what's coming.

This is something tooling should fix.

See:
- https://github.com/alanshaw/david/issues/17
- https://github.com/dylang/changelog
- https://github.com/bahmutov/changed-log

I'm open to suggestions, but I'm not interested in having a noop bin just because people are lazy.

**Comment by developit** [comment]
That works for me - I agree it's a bit gross to retain old files not for compatibility but for notification purposes.  Would absolutely love to see something in NPM about this.  Even something as simple as a "package exports have changed" type warning since it'd be pretty easy to detect changes to `"main" or `"bin"`.

**Comment by sindresorhus** [comment]
I tried to get a way to make version announcements with npm, but as with most good ideas on the npm issue tracker, it was ignored. https://github.com/npm/npm/issues/4184

Also see: https://github.com/npm/npm/issues/5851

You should open an issue on the npm issue tracker about this problem ;)
